<?php

namespace ApartmentTest\Model;

use Apartment\Model\User;

/**
 * Test class for User.
 * Generated by PHPUnit on 2013-11-03 at 17:18:13.
 */
class UserTest extends \PHPUnit_Framework_TestCase {
	
	// Testen, dass am Anfang die Attribute nicht gesetzt sind
	public function testUserInitialState() {
		$user = new User ();
		
		$this->assertNull ( $user->admin );
		$this->assertNull ( $user->apartment_id );
		$this->assertNull ( $user->name );
		$this->assertNull ( $user->password );
	}
	public function testExchangeArraySetsPropertiesCorrectly() {
		$user = new User ();
		
		$data = array (
				
				'name' => 'bla',
				'password' => 'blabla',
				'apartment_id' => 1,
				'admin' => true 
		);
		
		$user->exchangeArray ( $data );
		
		$this->assertSame ( $data ['name'], $user->name );
		$this->assertSame ( $data ['password'], $user->password );
		$this->assertSame ( $data ['apartment_id'], $user->apartment_id );
		$this->assertSame ( $data ['admin'], $user->admin );
	}
	public function testExchangeArraySetsPropertiesToNullIfKeysAreNotPresent() {
		$user = new User ();
		
		$data = array (
				
				'name' => 'bla',
				'password' => 'blabla',
				'apartment_id' => 1,
				'admin' => true 
		);
		
		$user->exchangeArray ( $data );
		$user->exchangeArray ( array () );
		
		$this->assertNull ( $user->admin );
		$this->assertNull ( $user->apartment_id );
		$this->assertNull ( $user->name );
		$this->assertNull ( $user->password );
	}
}
?>
