<html>

<head>

<style type="text/css">
td,th {
	padding: 10px;
	text-align: left;
}

.button_dropdown {
	float: right;
}

#container {
	text-align: center;
	position: relative;
}

#background {
	width: 100%;
	height: 100%;
}

.light {
	width: 35px;
	height: 35px;
}

#light_kitchen {
	position: absolute;
	bottom: 35px;
	right: 730px;
}

#light_bathroom {
	position: absolute;
	bottom: 240px;
	right: 760px;
}

#light_living {
	position: absolute;
	bottom: 150px;
	right: 450px;
}
}
</style>



<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>



<script>


	$(document).ready(function() {
			
		//Funktion fuer die Dropdown Liste
		$(".button_dropdown").click(function() {

			var index = $(".button_dropdown").index(this);

			var table_sel = "#tabelle" + index;
			var button_sel = "#button_table_" + index;
			var div_sel = "#div_dropdown_" + index;

			//Toggeln der Tabelle
			
			
			
			$(div_sel).toggle();

			//Ändern des Knopftexts
			$(button_sel).text(function(i, oldText) {

				if (oldText == "+") {

					return "-";
				} else {
					return "+";
				}
			});
		});

		//Funktion, mit der das Anschalten eines Lichts gemacht wird
		$(".button_light").click(function(){

			
			var index = $(".button_light").index(this);
			var buttonId = "#button_light_" + index;
			var nameId = "#room_name_light_" + index;
			var statusId = "#status_light_" + index;

			var roomName = $(nameId).text();

			var myData = {

					zimmername : roomName,
					wohnungsnummer : <?php echo $apartment->id?>

					};

			$.ajax({

				type:"POST",
				url: "<?php echo $this->basePath();?>/enter/toggleLight",
				data:myData,
				success:function(data){

					//Anpassen des Knopftexts
					$(buttonId).text(data.button);
					//Anpassen des Status
					$(statusId).text(data.status);
					//Anpassen des GesamtLichtverbrauchs
					$("#text_power_sum_light").text(data.power_sum);
					//Anpassen des Gesamtverbrauchs der Wohnung
					$("#text_apartment_power").text(data.power_apartment);

					switch (data.room_name) {
					case "Kueche":
						
						if(data.status == "An"){
							
						$("#img_light_kitchen").attr("src", "<?php echo $this->basePath();?>/img/gluehbirne_an.png");
						}else{
						$("#img_light_kitchen").attr("src", "<?php echo $this->basePath();?>/img/gluehbirne_aus.png");
						}
						break;

					case "Bad":
						if(data.status == "An"){
							
						$("#img_light_bathroom").attr("src", "<?php echo $this->basePath();?>/img/gluehbirne_an.png");
						}else{
						$("#img_light_bathroom").attr("src", "<?php echo $this->basePath();?>/img/gluehbirne_aus.png");
						}
						break;

					case "Zimmer_1":
						if(data.status == "An"){
							
						$("#img_light_living").attr("src", "<?php echo $this->basePath();?>/img/gluehbirne_an.png" );
						}else{
						$("#img_light_living").attr("src", "<?php echo $this->basePath();?>/img/gluehbirne_aus.png" );
						}
						break;

					default:
						break;
					}

					},
				failure:function(){
					alert("Post has failed");
					}


				});


			});

		//Funktion, mit der man alle Lichter ausschaltet
		$("#button_lightsout_all").click(function(){

			var myData = {
					wohnungsnummer:<?php echo $apartment->id?>

					};
			
			$.ajax({
					type:"POST",
					url:"<?php echo $this->basePath();?>/enter/allLightsOut",
					data:myData,
					success:function(data){

						// Alle Buttons auf an 
						$(".button_light").text("An");
						// Alle Status auf aus
						$(".status_light").text("Aus");
						// Lichtverbrauch auf 0
						$("#text_power_sum_light").text("0");
						// Gesamtverbrauch anpassen
						$("#text_apartment_power").text(data.gesamtverbrauch);

						// Change all pictures to the off light
						$('.img_light').attr('src', '<?php echo $this->basePath();?>/img/gluehbirne_aus.png');
						
						

						},
					failure:function(){
					alert("the post of the allLightsOut has failed");
						}
	
				});



			});

		//Funktion, mit der man eine Solltemperatur einstellt

		$(".set_temperature").click(function(){

			var index = $(".set_temperature").index(this);
			var nameSel = "#temp_name_" + index;
			var sollSel = "#temp_soll_" + index;
			var verbrauchSel = "#temp_verbrauch_" + index;
			var inputSel = "#temp_input_" + index;

			var sollTemp = $(inputSel).val();
			if (sollTemp !=  ""){
			sollTemp = Math.round(sollTemp);
			var name = $(nameSel).text();
			
			var myData = {
					'sollTemp':sollTemp,
					'wohnungsnummer': <?php echo $apartment->id?>,
					'name':name		
					};

			$.ajax({

				type:"POST",
				url:"<?php echo $this->basePath();?>/enter/changeTemp",
				data:myData,
				success:function(data){

						

						// Anpassen des gesamtverbrauchs, der Solltemperatur, des Zimmerverbrauchs und des Wohnungstempverbrauchs
						$(sollSel).text(sollTemp);
						$("#text_apartment_power").text(data.gesamtverbrauch);
						$("#text_temp_gesamt").text(data.tempverbrauch_wohnung);
						$(verbrauchSel).text(data.tempverbrauch_zimmer);
						
					
					},
				failure:function(){alert("Failure TempChange");}
				});
			
			}			


			});

		// Funtion, um alle Heizungen/Klimaanlagen abzuschalten

		$("#button_temp_all_off").click(function(){

			// Der Server bekommt die Nummer der Wohnung und den GesamtTemperaturVerbrauch

			var id = <?php echo $apartment->id?>;
			var temp_verbrauch = $("#text_temp_gesamt").text();

			var myData = {
					'id':id,
					'temp_verbrauch':temp_verbrauch
					};

			$.ajax({

				type:"POST",
				url:"<?php echo $this->basePath();?>/enter/allTempOff",
				data:myData,
				success:function(data){
					
					var gesamtverbrauch = data.gesamtverbrauch;
					$("#text_apartment_power").text(gesamtverbrauch);
					$('#text_temp_gesamt').text(0);

					// Anpassen aller Soll- an die Aussentemperaturen
					$(".temp_soll").text(function(index, text){

						var temp_aussen_sel = "#temp_aussen_" + index;

						return $(temp_aussen_sel).text();

						});

					// Heruntersetzen aller Verbrauche der Zimmer
					$(".temp_verbrauch").text(0);

					},
				failure:function(){
					alert("post alltempoff failed");
					}	
				});


			});

		
		

		
	});
	
</script>





</head>

<!-- Alle Tabellen erstmal ausblenden -->



<?php
$title = "Die Wohnung Nummer " . $apartment->id;

if ($rooms == null) {
	throw new \Exception ( "No rooms given to the view" );
}

if ($apartment == null) {
	throw new \Exception ( "No apartment given to the view" );
}

$this->headTitle ( $title );

// Determine which state the lights represented by the pictures are in

$rooms->buffer ();

foreach ( $rooms as $room ) {
	
	$name = $room->name;
	
	switch ($name) {
		case "Kueche" :
			$light_kitchen = $room->light;
			break;
		case "Bad" :
			$light_bath = $room->light;
			break;
		case "Zimmer_1" :
			$light_living = $room->light;
			break;
		default :
			break;
	}
}

?>


<body>
	<h1>
		<?php echo $this->escapeHtml($title);?>
	</h1>

	<hr>

	<!-- 	Allgemeine Daten -->

	<h3>
		Allgemeine Daten
		<button type="button" id="button_table_0" class="button_dropdown">+</button>
	</h3>



	<div class="div_dropdown" id="div_dropdown_0" hidden="true">
		<table id="tabelle0">
			</tr>
			<tr>
				<td>Adresse:</td>
				<td>
				<?php echo $this->escapeHtml($apartment->adress)?>
			</td>
			</tr>
			<tr>
				<td>Stockwerk:</td>
				<td>
				<?php echo $this->escapeHtml($apartment->floor)?>
			</td>
			</tr>
			<tr>
				<td>Gesamtverbrauch:</td>
				<td id="text_apartment_power">
				<?php
				
				if ($apartment->power == 0) {
					echo "0";
				} else {
					
					echo $this->escapeHtml ( $apartment->power );
				}
				?>
			</td>
			</tr>



		</table>
	</div>

	<hr>

	<!-- 		Licht -->

	<h3>
		Beleuchtung
		<button type="button" id="button_table_1" class="button_dropdown">+</button>
	</h3>

	<div class="div_dropdown" id="div_dropdown_1" hidden="true">

		<div id="container">

			<div id="background">
				<img alt="apartment_picture"
					src=<?php echo $this->basePath('img/praterstr3.jpg')?>>
			</div>



			<div id="light_kitchen" class="light">
				<img class="img_light" id="img_light_kitchen" alt="gluehbirne_aus"
					src=<?php
					if ($light_kitchen) {
						echo $this->basePath ( 'img/gluehbirne_an.png' );
					} else {
						echo $this->basePath ( 'img/gluehbirne_aus.png' );
					}
					?>>
			</div>

			<div id="light_bathroom" class="light">
				<img class="img_light" id="img_light_bathroom" alt="gluehbirne_aus"
					src=<?php
					
					if ($light_bath) {
						echo $this->basePath ( 'img/gluehbirne_an.png' );
					} else {
						echo $this->basePath ( 'img/gluehbirne_aus.png' );
					}
					?>>
			</div>

			<div id="light_living" class="light">
				<img class="img_light" id="img_light_living" alt="gluehbirne_aus"
					src=<?php
					
					if ($light_living) {
						echo "'" . $this->basePath ( 'img/gluehbirne_an.png' ) . "'";
					} else {
						echo "'" . $this->basePath ( 'img/gluehbirne_aus.png' ) . "'";
					}
					?>>
			</div>

		</div>

		<table id="tabelle1">

			<tr>
				<td>Gesamtverbrauch</td>
			<?php
			
			// Ausrechnen des Gesamtlichtverbrauchs
			
			$powerSum = 0;
			foreach ( $rooms as $room1 ) {
				
				$powerSum = $powerSum + $room1->power_light;
			}
			
			?>
			<td id="text_power_sum_light"><?php echo $powerSum?></td>
				<td><button id="button_lightsout_all">Alle Lichter Ausschalten</button></td>

			</tr>

			<tr>

				<th>Zimmer</th>
				<th>Licht</th>

			</tr>

		<?php
		$counter = - 1;
		
		foreach ( $rooms as $room ) :
			
			?>

		<?php $counter++;?>


		<tr>

				<td class="room_name_light"
					id=<?php echo "room_name_light_" . $counter?>><?php echo $this->escapeHtml($room->name);?>
			</td>

			<?php
			
			if ($room->light == 0) {
				
				$light = "Aus";
				$button = "An";
			} else {
				$light = "An";
				$button = "Aus";
			}
			
			?>

			<td class="status_light" id=<?php echo "status_light_" . $counter?>><?php echo $light;?></td>

				<td><button class="button_light"
						id=<?php echo "button_light_" . $counter?>>
					<?php echo $button;?></button></td>

			</tr>

		<?php endforeach;?>

	</table>
	</div>

	<hr>

	<!-- 	Temperatur -->

	<h3>
		Temperatur
		<button type="button" id="button_table_2" class="button_dropdown">+</button>
	</h3>

	<div class="div_dropdown" id="div_dropdown_2" hidden="true">
		<table id="tabelle2">

			<tr>

				<td>Gesamtverbrauch</td>
			<?php
			// erechnen des gesamtVerbrauchs der Heizung
			$sum = 0;
			foreach ( $rooms as $room ) {
				
				$sum = $sum + $room->power_temperature;
			}
			
			?>
			<td id="text_temp_gesamt"><?php echo $sum?></td>
				<td id="button_temp_all_off"><button>Alle Heizungen/Klimaanlagen
						ausschalten</button></td>

			</tr>

			<tr>

				<th>Zimmer</th>
				<th>Solltemperatur</th>
				<th>Aussentemperatur</th>
				<th>Energieverbrauch</th>


			</tr>

		<?php
		$counter = - 1;
		foreach ( $rooms as $room ) :
			$counter ++;
			$room->prepareData ();
			?>
		
		<tr>

				<td id=<?php echo "temp_name_" . $counter?>>
				<?php echo $this->escapeHtml($room->name);?>
			</td>
				<td id=<?php echo "temp_soll_" . $counter?> class="temp_soll">
				<?php echo $room->temperature?>
			</td>
				<td id=<?php echo "temp_aussen_" . $counter?> class="temp_aussen">
				<?php echo $room->temperature_outside?>
			</td>
				<!-- Energieverbrauch -->
				<td class="temp_verbrauch"
					id=<?php echo "temp_verbrauch_" . $counter?>><?php
			
			echo $room->power_temperature;
			
			?></td>
				<td>Solltemperatur: <input type="number"
					value=<?php echo $room->temperature;?>
					id=<?php echo "temp_input_" . $counter?>></td>
				<td><button class="set_temperature"
						id=<?php echo "temp_button_".$counter?>>Einstellen</button></td>

			</tr>



		<?php endforeach;?>



	</table>
	</div>



	<hr>

	<h3>
		Sonstige Geraete
		<button id="button_table_3" class="button_dropdown">+</button>
	</h3>

	<div class="div_dropdown" id="div_dropdown_3" hidden="true">
		<table id="tabelle3">

			<tr>

				<td>Gesamtverbrauch</td>
				<td>0</td>
				<td><button>Alle Geraete ausschalten</button></td>

			</tr>

			<tr>

				<th>Zimmer</th>
				<th>Verbrauch der Geraete</th>
			</tr>

		<?php foreach ($rooms as $room):?>

		<tr>

				<td>
				<?php echo $this->escapeHtml($room->name);?>
			</td>
				<td>0</td>
				<td><button>Betreten</button></td>


			</tr>


		<?php endforeach;?>

	</table>
	</div>


</body>

</html>