<html>

<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>


<script>

// Script to remove the links to the profile and the logout
	$(document).ready(function(){

		$('#profile_link').toggle();
		$('#logout_link').toggle();


		});

</script>


<body>
<h1>Beispiele von den Elementen aus dem Twitter Bootstrap</h1>

<hr>

<h2>Buttons</h2>



<button class="btn-default">default</button><br>
<button class="btn-primary">primary</button><br>
<button class="btn-success">success</button><br>
<button class="btn-info">info</button><br>
<button class="btn-warning">warning</button><br>
<button class="btn-danger">danger</button><br><br>









</body>
</html>